package com.triples.authentication.model;

public enum BankingRole {
    BANK_TELLER,
    CUSTOMER_SERVICE_REPRESENTATIVE,
    LOAN_OFFICER,
    BRANCH_MANAGER,
    RELATIONSHIP_MANAGER,
    INVESTMENT_BANKER,
    FINANCIAL_ANALYST,
    RISK_MANAGER,
    COMPLIANCE_OFFICER,
    AUDITOR,
    DATA_ANALYST,
    TREASURY_ANALYST,
    IT_SPECIALIST,
    CREDIT_ANALYST,
    FOREX_TRADER,
    PRIVATE_BANKER,
    OPERATIONS_MANAGER,
    COMPLIANCE_SPECIALIST,
    CREDIT_RISK_MANAGER,
    INVESTMENT_PORTFOLIO_MANAGER,
}
